Repository prgrms-fe-devcourse/FEDC3_POMO_DY, pull requests merged in 2023-01, with the labels that each got.

#6 chore/4: lint-staged, husky 세팅
  .husky/pre-commit
  package-lock.json
  package.json
Labels: 📦 chore

#8 chore/7: 라이브러리 세팅
  package-lock.json
  package.json
Labels: 📦 chore

#9 chore: PR 템플릿 생성
  .github/pull_request_template.md
Labels: 📦 chore

#10 chore: 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/♻️-리펙토링-요청.md
  .github/ISSUE_TEMPLATE/✨-기능-요청.md
  .github/ISSUE_TEMPLATE/🐛-버그-리포트.md
  .github/ISSUE_TEMPLATE/📦-잡일-요청.md
Labels: 📦 chore

#11 chore: 스타일 관련 초기 세팅
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  public/fonts/UhBee EUN KYUNG.ttf
  public/fonts/index.css
  styles/colors.ts
  styles/global.ts
  styles/reset.ts
Labels: 📦 chore

#15 회원가입 (create) 마크업
  pages/create/index.tsx
  public/svg/logo.svg
Labels: ✨ featrue

#17 로그인 (login) 마크업
  pages/login/index.tsx
  public/svg/logo.svg
Labels: ✨ featrue

#18 리액트 쿼리 전역 설정
  pages/_app.tsx
Labels: 📦 chore

#30 logo.svg 코드 수정
  public/images/logo.svg
  public/svg/logo.svg
Labels: 🐛 fix

#24 chore: axiosInstance 만들기
  api/index.ts
Labels: 📦 chore

#35 fix: svg import 경로 수정
  pages/login/index.tsx
Labels: 🐛 fix

#37 회원 가입 기능 1차 개발 완료
  pages/sign/index.tsx
Labels: ✨ featrue

#45 chore: svg rect가 path로 렌더링되지 않도록
  next.config.js
Labels: 🐛 fix

#41 feat: 뽀모도로 페이지 > 탭 영역 마크업
  .vscode/settings.json
  components/post/pomodoro/tabs/CommentItem.tsx
  components/post/pomodoro/tabs/CommentList.tsx
  components/post/pomodoro/tabs/ParticipantItem.tsx
  components/post/pomodoro/tabs/ParticipantList.tsx
  components/post/pomodoro/tabs/index.tsx
  package-lock.json
  package.json
  pages/post/[categoryId]/[postId].tsx
  public/icons/circle_arrow.svg
  public/icons/profile.svg
  styles/global.ts
Labels: ✨ featrue

#51 Github Actions에 빌드 테스트 추가
  .github/workflows/build-test.yml
Labels: 📦 chore

#38 로그인 기능 1차 개발 완료
  pages/login/index.tsx
  pages/sign/index.tsx
Labels: ✨ featrue

#59 fix: 빌드 테스트에 yarn이 아닌 npm 사용하도록 수정
  .github/workflows/build-test.yml
Labels: 🐛 fix

#62 post 폴더 posts와 post로 분리하기로 한 것 뽀모도로 페이지 컴포넌트들에 반영
  components/post/tabs/CommentItem.tsx
  components/post/tabs/CommentList.tsx
  components/post/tabs/ParticipantItem.tsx
  components/post/tabs/ParticipantList.tsx
  components/post/tabs/index.tsx
  pages/post/[categoryId]/[postId].tsx
Labels: ♻️ refactor

#46 feat: 메인 페이지 기본 마크업 & UI 완성
  components/home/CategoryCard.tsx
  components/home/UserCard.tsx
  pages/index.tsx
  public/images/icon/person.svg
  public/images/icon/search.svg
  public/images/tomato.svg
Labels: ✨ featrue

#66 refactor: icons 폴더 통합
  pages/index.tsx
  public/icons/search.svg
  public/images/icon/person.svg
Labels: ♻️ refactor

#52 유저 정보 조회 마크업
  components/profile/index.tsx
  pages/profile/[id].tsx
  pages/profile/index.tsx
  public/icons/follow.svg
  public/icons/pencil.svg
Labels: ✨ featrue

#44 feat: 뽀모 모집글 생성페이지 마크업
  components/post/create/Input.tsx
  components/post/create/index.tsx
  pages/post/create/index.tsx
Labels: ✨ featrue

#71 feat: 메인 페이지 카드 목록 api 연동
  components/home/CategoryCard.tsx
  pages/index.tsx
Labels: ✨ featrue

#64 feat: 모집 글 목록 페이지 마크업 & UI
  components/posts/PostCard.tsx
  pages/post/[categoryId].tsx
  public/icons/left_arrow.svg
Labels: ✨ featrue

#82 feat: next api 설정
  .gitignore
  api/index.ts
  pages/api/channels.ts
  pages/api/login.ts
  pages/api/signup.ts
Labels: ✨ featrue

#42 feat: 네비게이션 바 마크업
  components/common/Header.tsx
  components/common/Search.tsx
  pages/_app.tsx
  public/images/logo-small.svg
  public/images/notification.svg
  public/images/profile.svg
  public/images/search.svg
Labels: ✨ featrue

#81 뽀모도로 페이지 > 탭 초기 상태 열려 있도록 하기
  components/post/tabs/index.tsx
Labels: 🐛 fix

#79 뽀모도로 페이지 > 글 정보 영역 구현
  components/post/constants.ts
  components/post/hooks/queries.ts
  components/post/info/index.tsx
  components/post/tabs/index.tsx
  components/post/types.ts
  pages/_app.tsx
  pages/api/posts/[postId].ts
  pages/post/[categoryId]/[postId].tsx
  styles/reset.ts
Labels: ✨ featrue

#91 fix: axios timeout 늘리기
  api/index.ts
Labels: 🐛 fix

#92 React Query 불필요한 refetch 되지 않도록 설정
  pages/_app.tsx
Labels: 📦 chore

#90 fix: next api 연결
  pages/index.tsx
  pages/login/index.tsx
  pages/sign/index.tsx
Labels: 🐛 fix

#95 chore: 인증 토큰 axiosInstance 설정 임시 처리
  api/index.ts
Labels: 📦 chore

#73 feat: 메인 페이지 유저 리스트 기능 구현
  components/home/CategoryCard.tsx
  components/home/UserCard.tsx
  components/home/types.ts
  pages/index.tsx
Labels: ✨ featrue

#83 feat: 검색 결과 UI 구현
  components/common/Header.tsx
  components/common/Search.tsx
  public/images/search.svg
Labels: ✨ featrue

#98 refactor: get-users api 호출 방식 변경
  pages/api/users/get-users.ts
  pages/index.tsx
Labels: ♻️ refactor

#69 유저인증 및 로그인 연결
  api/index.ts
  components/auth/authrequire.tsx
  components/auth/checkToken.tsx
  components/auth/localstorage.tsx
  components/login/loginApi.tsx
  pages/api/authUser.ts
  pages/api/sign.ts
  pages/index.tsx
  pages/login/index.tsx
  pages/sign/index.tsx
Labels: ✨ featrue

#101 뽀모도로 페이지 > 댓글 기본 기능 구현
  components/post/constants.ts
  components/post/hooks/queries.ts
  components/post/hooks/useComments.ts
  components/post/styles.ts
  components/post/tabs/CommentList.tsx
  components/post/tabs/ParticipantList.tsx
  components/post/tabs/comment/CommentItem.tsx
  components/post/tabs/comment/index.tsx
  components/post/tabs/index.tsx
  components/post/tabs/participant/ParticipantItem.tsx
  components/post/tabs/participant/index.tsx
  components/post/types.ts
  pages/api/comments/create.ts
  pages/api/posts/[postId].ts
  pages/post/[categoryId]/[postId].tsx
Labels: ✨ featrue

#106 feat: 검색 이벤트 등록 및 API 연동
  components/common/Header.tsx
  components/common/Search.tsx
  pages/api/search/all/[keyword].ts
  public/images/post-index.svg
Labels: ✨ featrue

#110 fix: 메인페이지 css 수정
  components/home/UserCard.tsx
  pages/index.tsx
Labels: 🐛 fix

#116 feat: 공통 모달 컴포넌트 구현
  components/common/modal/index.tsx
  public/icons/close.svg
Labels: ✨ featrue

#104 feat: 카테고리 별 모집 글 페이지 기능 구현 완료
  components/home/CategoryCard.tsx
  components/home/types.ts
  components/posts/PostCard.tsx
  components/posts/types.ts
  components/posts/util.ts
  pages/api/posts/channel/[categoryId].ts
  pages/post/[categoryId].tsx
  pages/post/[categoryId]/index.tsx
  public/images/sad-tomato.svg
Labels: ✨ featrue

#119 fix: 검색 결과에 포스트 카테고리 미포함 문제 해결
  components/common/Header.tsx
Labels: 🐛 fix

#114 feat: 참여자 목록 api 연결
  api/post.ts
  components/post/constants.ts
  components/post/hooks/queries.ts
  components/post/hooks/useHost.ts
  components/post/hooks/useParticipants.ts
  components/post/tabs/participant/ParticipantItem.tsx
  components/post/tabs/participant/index.tsx
  components/post/types.ts
  next.config.js
  pages/api/posts/[postId].ts
Labels: ✨ featrue

#121 feat: 뽀모 나가기 경고 모달창 구현
  components/common/modal/index.tsx
  components/exit/index.tsx
  pages/exit/index.tsx
  public/images/logo-sad.svg
Labels: ✨ featrue

#120 feat: 네비게이션 바 페이지 이동 구현 & 네비게이션 바 노출 제한
  components/common/Header.tsx
  components/layout/BaseLayout.tsx
  pages/_app.tsx
Labels: ✨ featrue

#100 feat: 뽀모 모집글 입력 예외 처리, 생성 api 연결
  components/post/create/Input.tsx
  components/postCreate/hooks/usePostCreateForm.ts
  components/postCreate/index.tsx
  components/postCreate/input/index.tsx
  components/postCreate/types.ts
  components/postCreate/utils/date.ts
  components/postCreate/utils/time.ts
  components/postCreate/utils/validatePostCreateForm.ts
  pages/api/posts/create.ts
  pages/post/create/index.tsx
Labels: ✨ featrue

#124 feat: 뽀모도로 페이지 > 타이머 마크업
  .vscode/settings.json
  components/post/constants.ts
  components/post/time/index.tsx
  components/post/types.ts
  pages/post/[categoryId]/[postId].tsx
  public/images/clock.svg
  public/images/pomo-circle-white.svg
  public/images/pomo-circle.svg
Labels: ✨ featrue

#125 feat: 뽀모도로 페이지 > 뽀모도로 대기 중 화면 구현
  components/post/constants.ts
  components/post/hooks/useInterval.ts
  components/post/hooks/useWaitingTimer.ts
  components/post/time/index.tsx
  components/post/types.ts
  components/post/waiting/index.tsx
  pages/post/[categoryId]/[postId].tsx
Labels: ✨ featrue

#126 feat: 뽀모 모집글 목록 페이지 > 뽀모 모집글 상세 모달 연결
  components/common/modal/index.tsx
  components/common/modal/useBodyScrollLock.ts
  components/home/CategoryCard.tsx
  components/postDetails/fetchUsers.ts
  components/postDetails/index.tsx
  components/posts/PostCard.tsx
  components/posts/types.ts
  pages/api/likes/create.ts
  pages/modal/index.tsx
  pages/post/[categoryId]/index.tsx
Labels: ✨ featrue

#129 feat: 뽀모 생성 페이지 연동
  components/postCreate/hooks/usePostCreateForm.ts
  components/postCreate/utils/validatePostCreateForm.ts
  components/postDetails/index.tsx
  pages/api/posts/create.ts
  pages/post/create/[cid].tsx
Labels: ✨ featrue

#131 fix: 메인 페이지 css 수정
  components/home/UserCard.tsx
  pages/index.tsx
Labels: ✨ featrue

#132 fix: 진행중인 뽀모 click 비활성화
  components/posts/PostCard.tsx
Labels: ✨ featrue

#134 feat: 뽀모도로 타이머 구현
  components/post/constants.ts
  components/post/hooks/useCountDown.ts
  components/post/hooks/useInterval.ts
  components/post/hooks/usePomoTimer.ts
  components/post/time/Timer.tsx
  components/post/time/index.tsx
  components/post/time/utils.ts
  components/post/types.ts
  components/post/waiting/index.tsx
  pages/post/[categoryId]/[postId].tsx
Labels: ✨ featrue

#135 feat: 알람 기능 UI 구현
  components/common/Header.tsx
  components/common/Search.tsx
Labels: ✨ featrue

#137 feat: 뽀모도로 페이지 > 나가기 버튼 구현
  components/post/waiting/index.tsx
  pages/post/[categoryId]/[postId].tsx
Labels: ✨ featrue

#139 feat: 타이머 마크업
  components/post/time/Timer.tsx
  components/post/time/index.tsx
  pages/post/[categoryId]/[postId].tsx
Labels: ✨ featrue

#141 feat: 뽀모도로 페이지 > 반복 누적 횟수 조회
  components/post/hooks/usePomoTimer.ts
  components/post/info/index.tsx
  components/post/time/Timer.tsx
  components/post/time/index.tsx
  pages/post/[categoryId]/[postId].tsx
Labels: ✨ featrue

#143 feat: 집중 시간에 본인 댓글만 보이도록
  api/post.ts
  components/post/tabs/comment/CommentItem.tsx
  components/post/tabs/comment/index.tsx
  components/post/tabs/index.tsx
  components/post/types.ts
  pages/post/[categoryId]/[postId].tsx
Labels: ✨ featrue

#144 fix: 시작 시간 버그 fix
  pages/post/[categoryId]/[postId].tsx
Labels: 🐛 fix

#146 fix: 바뀐 백엔드 필드 이름 반영
  api/post.ts
  components/post/time/utils.ts
Labels: 🐛 fix

#147 fix: next api 활용하지 않도록
  components/post/hooks/queries.ts
  components/post/tabs/comment/index.tsx
  pages/post/[categoryId]/[postId].tsx
Labels: 🐛 fix

#149 Fix : 종료된 뽀모 방에 대한 처리
  components/home/CategoryCard.tsx
  components/posts/PostCard.tsx
  components/posts/util.ts
  pages/post/[categoryId]/index.tsx
Labels: 🐛 fix

#155 fix: 종료된 pomo는 모달 뜨지 않도록 수정
  components/posts/PostCard.tsx
Labels: 🐛 fix
